### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core.angular#1]
When I go to this repo I get the following:

<img width="994" alt="skarmavbild 2018-07-23 kl 06 08 28" src="https://user-images.githubusercontent.com/781266/43056856-f4d0f4ac-8e3e-11e8-8b39-92f1fa7bf303.png">

I have no idea what it is, but it doesn't look good :)

**Comment by jcphlux** [comment]
Sorry about that. I need to create a dev branch. I tend to commit and push when I am done for the night.

**Comment by jcphlux** [comment]
@tidyui  can you grant me access to vulnerability alerts on this repo?

**Comment by jcphlux** [comment]
@tidyui I have the site finished and have pushed all my changes. Are you still seeing this warning? 
I am going to start working on the NuGet package next.

**Comment by tidyui** [comment]
Yes, here are the details!

![bd20d315-3bd1-421e-8bdb-35009b2627e6](https://user-images.githubusercontent.com/781266/43365522-544524be-932e-11e8-9841-4c0092f0a55c.jpeg)

**Comment by jcphlux** [comment]
I am looking at this now. Not sure why but GitHub did not give me notice that you added a comment.

**Comment by jcphlux** [comment]
@tidyui Can you check if the issue is resolved now?

**Comment by tidyui** [comment]
Still the same, but one more error!
<img width="749" alt="skarmavbild 2018-08-31 kl 14 02 05" src="https://user-images.githubusercontent.com/781266/44911267-92ea6f00-ad26-11e8-91d7-1417bc79c96f.png">

**Comment by jcphlux** [comment]
Interesting. When I do an npm audit it comes up clean.

**Comment by jcphlux** [comment]
@tidyui I think I got it. I had to do a bunch of pushs to figure it out because github and npm are not on the same page as to what is a vulnerability. 

BTY I have enabled all my security alert setting but I still dont get the nice little yellow boxs you are getting on the Dependency graph.

**Comment by jcphlux** [comment]
@tidyui are you still getting errors on this?
